name: code
description: A AI Agent Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.3
  shared_preferences: ^2.2.2
  riverpod_annotation: ^2.2.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.2.0
  dio: ^5.7.0
  retrofit: ^4.4.0
  logger: ^2.4.0
  go_router: ^14.6.3
  fluttertoast: ^8.2.10
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  pdfrx: ^1.0.101
  firebase_storage: ^12.4.1
  flutter_pdfview: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  riverpod_generator: ^2.3.9
  json_serializable: ^6.8.0
  retrofit_generator: ^9.0.0

flutter:

  uses-material-design: true
  assets:
    - .env.development
    - .env.staging
    - .env.production
    - assets/
